### ISSUE TITLE
The plugin does not work anymore

### ISSUE THREAD

**Issue by Chardonneaur** [sms77io/matomo#1]
Hi,
I tested at least two times this plugin over the last 3 months and it never worked.
I contacted the support through sms77.io and got no answers.

**Comment by matthiez** [comment]
Hi,
sorry for that!
I just released v1.2.0 which should have fixed the problem. I guess it takes some time until the marketplace gets updated though.

**Comment by Chardonneaur** [comment]
oh great, that's really unexpected, I tried your platform and did not receive any messages in order to validate my phone number. BTW, would you be interested in being a speaker at next MatomoCamp: https://matomocamp.org ?

**Comment by Chardonneaur** [comment]
@matthiez the link does not work https://github.com/seven-io/matomo/releases/download/v1.2.0/sms77-matomo-latest.zip

**Comment by Chardonneaur** [comment]
@matthiez I just installed v1.2 directly from the github repository, seems better but I am not receiving any sms validation message.

**Comment by matthiez** [comment]
> @matthiez I just installed v1.2 directly from the github repository, seems better but I am not receiving any sms validation message.

I can not seem to reproduce this. Can you please tell me the Matomo version used?
Also, did you use a live API key or sandbox? Sandboxed API key's don't send out messages. You can still obtain the validation code from your [developer dashboard](https://app.sms77.io/developer).

**Comment by Chardonneaur** [comment]
@matthiez I tried again but still not working. But even if it was working, it seems that the send sms report within Matomo does not work neither (not recognizing the phone number I added into mobile messaging). I am using Matomo 4.11.

**Comment by matthiez** [comment]
> @matthiez I tried again but still not working. But even if it was working, it seems that the send sms report within Matomo does not work neither (not recognizing the phone number I added into mobile messaging). I am using Matomo 4.11.

Sorry for answering late, but I was busy all the time.
I will try again with 4.11 ASAP. I tried with 4.10.1, I think. Nothing regarding the reporting has been changed though, at least according to the changelog.
What format did you use when adding the phone number?
+49123456
49123456
0049123456
etc...

**Comment by Chardonneaur** [comment]
Hello,
I tried all of them.

**Comment by matthiez** [comment]
Very strange.
I have upgraded Matomo to 4.11.0 and just now successfully sent reports with both PHP 7.3 and 7.4.
What PHP version are you using?

**Comment by Chardonneaur** [comment]
PHP 8, I am going to give it another try. Thanks for your effort.

**Comment by Chardonneaur** [comment]
@matthiez hi, I gave it another try today and I am getting an error when validating the report to send by sms. It is telling me that i didn't set any parameter in the report whereas I did.
Would you be available for a conference call so that we can fix all issues?

**Comment by matthiez** [comment]
> @matthiez hi, I gave it another try today and I am getting an error when validating the report to send by sms. It is telling me that i didn't set any parameter in the report whereas I did. Would you be available for a conference call so that we can fix all issues?

Hi,
so I just published a new version to the marketplace. I am pretty sure that it will work now. For some reason, v1.2.0 was never recognized by the marketplace. Probably because we changed the GitHub organization name from sms77io to seven-io. This is also why the links in the listing throws 404 errors. I will try to fix that soon.

**Comment by Chardonneaur** [comment]
@matthiez thank you but it still does not work. The 404 are corrected but when i try to send the report, i am getting an error message.
![sms77](https://user-images.githubusercontent.com/28002238/201684216-7211a6b4-bff3-488b-b77d-472d67509a61.png)

**Comment by matthiez** [comment]
@Chardonneaur 
Ah, now I understand. You just need to add a phone number first on the _Mobile Messaging page, /index.php?module=MobileMessaging&action=index.

<img width="974" alt="image" src="https://user-images.githubusercontent.com/12965261/201720130-c242f7ef-106b-4152-b9ed-7ff5e59cefb8.png">

After adding, you can select it in the _Envoyer le(s) rapport(s) à_.

**Comment by Chardonneaur** [comment]
ok finally get it, for some reasons, I am not receiving codes on my smartphone but on sms77 backend. Now it works, thanks
